---
- alias: 'Hass Startup Notification'
  trigger:
    - platform: 'homeassistant'
      event: 'start'
  action:
    - service: 'notify.bertie_iphone'
      data:
        message: 'ğŸŒµ Home Assistant has started'
